log_path: "lillipub.log"

site_location: "/home/brettk/blog"
site_url: "http://blog.b-ark.ca"

media_endpoint: "https://media.org/endpoint"
token_endpoint: "https://tokens.indieauth.com/token"

date_format: "%Y-%m-%d %H:%M:%S %z"

feed:
  uid: "4A75D60C-5F78-4C0C-8C6A-B3B15255B4BD"
  name: "The 'B' Ark"

add_type_category: true

front_matter:
  article:
    summary: :summary
  like:
    like_of: :like-of
  repost:
    repost_of: :repost-of
  bookmark:
    bookmark_of: :bookmark-of
  categories:
    tweet:
      syndicate_to: [ twitter ]
  all:
    layout: :type
    title: :name
    author: "Brett Kosinski"
    date: :published
    category: :category
    in_reply_to: :in-reply-to
